info:
  app:
    name: '@info.app.name@'
    version: '@info.app.version@'
    grailsVersion: '@info.app.grailsVersion@'
grails:
  controllers:
    defaultScope: singleton
  views:
    default:
      codec: html
    gsp:
      encoding: UTF-8
      htmlcodec: xml
      codecs:
        expression: html
        scriptlet: html
        taglib: none
        staticparts: none
  mime:
    disable:
      accept:
        header:
          userAgents:
            - Gecko
            - WebKit
            - Presto
            - Trident
    types:
      all: '*/*'
      atom: application/atom+xml
      css: text/css
      csv: text/csv
      form: application/x-www-form-urlencoded
      html:
        - text/html
        - application/xhtml+xml
      js: text/javascript
      json:
        - application/json
        - text/json
      multipartForm: multipart/form-data
      pdf: application/pdf
      rss: application/rss+xml
      text: text/plain
      hal:
        - application/hal+json
        - application/hal+xml
      xml:
        - text/xml
        - application/xml
dataSource:
  pooled: true
  jmxExport: true
  driverClassName: com.mysql.cj.jdbc.Driver
  username: tu_usuario
  password: tu_contrase単a
  dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  url: jdbc:mysql://localhost:3306/db_lopez
  dbCreate: update
hibernate:
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
environments:
  development:
    dataSource:
      dbCreate: update
      url: jdbc:mysql://localhost:3306/db_lopez
      driverClassName: com.mysql.cj.jdbc.Driver
      username: tu_usuario
      password: tu_contrase単a
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  test:
    dataSource:
      dbCreate: update
      url: jdbc:mysql://localhost:3306/db_lopez
      driverClassName: com.mysql.cj.jdbc.Driver
      username: tu_usuario
      password: tu_contrase単a
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  production:
    dataSource:
      dbCreate: none
      url: jdbc:mysql://localhost:3306/db_lopez
      driverClassName: com.mysql.cj.jdbc.Driver
      username: tu_usuario
      password: tu_contrase単a
      dialect: org.hibernate.dialect.MySQL5InnoDBDialect
